keep track of the dir to go towards the trader
For the record, this is where I ran into the following ICE, with a small addition afterwards to add the `backward` method.

$ cargo build --verbose
       Fresh cc v1.0.71
       Fresh fs_extra v1.2.0
       Fresh xs v0.1.0 (/home/ryan/code/rust/guilloché/xs)
       Fresh lazy_static v1.4.0
       Fresh cmake v0.1.46
   Compiling stbhw v0.1.0 (/home/ryan/code/rust/guilloché/stbhw)
       Fresh tile v0.1.0 (/home/ryan/code/rust/guilloché/tile)
     Running `/home/ryan/code/rust/guilloché/target/debug/build/stbhw-e027be8695e92f9f/build-script-build`
       Fresh libc v0.2.104
       Fresh raylib-sys v3.5.0
       Fresh raylib v3.5.0
     Running `rustc --crate-name stbhw --edition=2021 stbhw/./src/stbhw.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ca7302517ef103ed -C extra-filename=-ca7302517ef103ed --out-dir '/home/ryan/code/rust/guilloché/target/debug/deps' -C 'incremental=/home/ryan/code/rust/guilloché/target/debug/incremental' -L 'dependency=/home/ryan/code/rust/guilloché/target/debug/deps' -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/stbhw-5787b0cda61d09d5/out' -l static=wrapper`
   Compiling game v0.1.0 (/home/ryan/code/rust/guilloché/game)
     Running `rustc --crate-name game --edition=2021 game/./src/game.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=1ef96814a811e1ee -C extra-filename=-1ef96814a811e1ee --out-dir '/home/ryan/code/rust/guilloché/target/debug/deps' -C 'incremental=/home/ryan/code/rust/guilloché/target/debug/incremental' -L 'dependency=/home/ryan/code/rust/guilloché/target/debug/deps' --extern 'stbhw=/home/ryan/code/rust/guilloché/target/debug/deps/libstbhw-ca7302517ef103ed.rmeta' --extern 'tile=/home/ryan/code/rust/guilloché/target/debug/deps/libtile-3fae7aac6ffcd7dc.rmeta' --extern 'xs=/home/ryan/code/rust/guilloché/target/debug/deps/libxs-14f8be66608ef0fe.rmeta' -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/stbhw-5787b0cda61d09d5/out'`
   Compiling guilloche v0.1.0 (/home/ryan/code/rust/guilloché/guilloche)
     Running `rustc --crate-name guilloche --edition=2021 guilloche/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=8620e167882b524d -C extra-filename=-8620e167882b524d --out-dir '/home/ryan/code/rust/guilloché/target/debug/deps' -C 'incremental=/home/ryan/code/rust/guilloché/target/debug/incremental' -L 'dependency=/home/ryan/code/rust/guilloché/target/debug/deps' --extern 'game=/home/ryan/code/rust/guilloché/target/debug/deps/libgame-1ef96814a811e1ee.rlib' --extern 'raylib=/home/ryan/code/rust/guilloché/target/debug/deps/libraylib-602e89fef42a7252.rlib' -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/stbhw-5787b0cda61d09d5/out' -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/raylib-sys-592fd42e671c84c5/out/lib' -L /usr/local/lib -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/raylib-sys-592fd42e671c84c5/out'`
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `guilloche`

Caused by:
  process didn't exit successfully: `rustc --crate-name guilloche --edition=2021 guilloche/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=8620e167882b524d -C extra-filename=-8620e167882b524d --out-dir '/home/ryan/code/rust/guilloché/target/debug/deps' -C 'incremental=/home/ryan/code/rust/guilloché/target/debug/incremental' -L 'dependency=/home/ryan/code/rust/guilloché/target/debug/deps' --extern 'game=/home/ryan/code/rust/guilloché/target/debug/deps/libgame-1ef96814a811e1ee.rlib' --extern 'raylib=/home/ryan/code/rust/guilloché/target/debug/deps/libraylib-602e89fef42a7252.rlib' -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/stbhw-5787b0cda61d09d5/out' -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/raylib-sys-592fd42e671c84c5/out/lib' -L /usr/local/lib -L 'native=/home/ryan/code/rust/guilloché/target/debug/build/raylib-sys-592fd42e671c84c5/out'` (exit status: 101)